name: worker
services:
  redis:
    image: redis:7-alpine
    platform: linux/amd64
    container_name: app_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery_worker:
    build: { context: ., dockerfile: Dockerfile }
    platform: linux/amd64
    container_name: celery_worker
    env_file: .env
    environment:
      CLOUDWATCH_LOG_GROUP: "/worker/logs"
      CLOUDWATCH_STREAM_PREFIX: "worker"
    command: celery -A app.celery_worker.celery_app worker --loglevel=info --concurrency=1 --prefetch-multiplier=1
    volumes:
      - ./app:/my-app/app
      - ./uploads:/my-app/uploads
      - ./processed:/my-app/processed
      - ./assets:/my-app/assets
    depends_on:
      redis: { condition: service_healthy }
    restart: unless-stopped
