name: worker
services:
  celery_worker:
    build: { context: ., dockerfile: Dockerfile }
    platform: linux/amd64
    container_name: celery_worker
    env_file: .env
    command: celery -A app.celery_worker.celery_app worker --loglevel=info --concurrency=1 --prefetch-multiplier=1
    volumes:
      - ./app:/my-app/app
      - ./uploads:/my-app/uploads
      - ./processed:/my-app/processed
      - ./assets:/my-app/assets
    restart: unless-stopped
