name: app 
services:
    postgres:
        image: postgres:16-alpine
        container_name: db_postgres
        environment:
            POSTGRES_USER: app_user
            POSTGRES_PASSWORD: app_password
            POSTGRES_DB: app_db
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432 || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: