"""Add new table vote; improve tables format

Revision ID: 5cd5af7206f3
Revises: aa87f25da68e
Create Date: 2025-10-13 23:50:55.487744

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cd5af7206f3"
down_revision: Union[str, None] = "aa87f25da68e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "videos", sa.Column("original_path", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "videos", sa.Column("processed_path", sa.String(length=500), nullable=True)
    )
    op.add_column("videos", sa.Column("task_id", sa.String(length=128), nullable=True))
    op.add_column("videos", sa.Column("user_id", sa.Integer(), nullable=False))
    op.add_column("videos", sa.Column("is_public", sa.Boolean(), nullable=True))
    op.add_column("videos", sa.Column("processed_at", sa.DateTime(), nullable=True))
    op.drop_index("ix_videos_id", table_name="videos")
    op.create_foreign_key(None, "videos", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "videos", type_="foreignkey")
    op.create_index("ix_videos_id", "videos", ["id"], unique=False)
    op.drop_column("videos", "processed_at")
    op.drop_column("videos", "is_public")
    op.drop_column("videos", "user_id")
    op.drop_column("videos", "task_id")
    op.drop_column("videos", "processed_path")
    op.drop_column("videos", "original_path")
    op.drop_table("votes")
    # ### end Alembic commands ###
