"""add constry and city in users

Revision ID: 788e10a12812
Revises: d662dc35ffd0
Create Date: 2025-10-15 11:49:57.738617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788e10a12812'
down_revision: Union[str, None] = 'd662dc35ffd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=255)))
    op.add_column('users', sa.Column('country', sa.String(length=255)))
    # ### end Alembic commands ###

    op.execute("UPDATE users SET city = '' WHERE city IS NULL")
    op.execute("UPDATE users SET country = '' WHERE country IS NULL")

    op.alter_column('users', 'city', nullable=False, existing_type=sa.String(length=255))
    op.alter_column('users', 'country', nullable=False, existing_type=sa.String(length=255))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
